[package]
name = "bitwise-calc"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
clear_screen = "0.1.0"
thiserror = "1.0.64"
ratatui = "0.28.1"
tui-big-text = "0.6.0"
crossterm = "0.28.1"
color-eyre = "0.6.3"